Pass a aiohttp session
annielcook/aio-plaid-python pull request #3
Opened 2020-01-13 03:19 UTC by lawrencealexander10

Allows user to pass in an existing http request connection for the purposes of making api calls. I just noticed that it would probably be useful to by default instantiate one aiohttp client session with the creation of a Client Object if one is not provided. I can make that update as well

2020-01-19 17:32 UTC, annielcook requested changes
This looks good. I left one comment about removing a commented out line. In regards to your comment about opening a session if one is not provided, I am not sure we should add that yet. Any logic for opening a session should have corresponding logic to ensure that session gets closed. I like your current implementation because that setup/teardown logic is handled by the app rather than this library. But if we opened a session in this library, then we would need to add the teardown logic here too.

2020-01-19 17:32 UTC, annielcook commented on plaid/requester.py
> +        # async with aiohttp.ClientSession() as session:
Remove this commented out line

2020-01-25 02:21 UTC, lawrencealexander10 commented on plaid/requester.py
> +        # async with aiohttp.ClientSession() as session:
Ammended

2020-01-25 21:32 UTC, merged

2020-01-25 21:32 UTC, annielcook commented on plaid/requester.py
> +        # async with aiohttp.ClientSession() as session:
Perf!